/*
 * Copyright 2006-2018 Adrian Thurston <thurston@colm.net>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <stdbool.h>
#include <iostream>

#include "compiler.h"

using namespace std;

/* Helper function to escape special characters in EBNF strings */
static void escapeEbnfString( ostream &out, const String &str )
{
	for ( const char *p = str.data; *p != 0; p++ ) {
		switch ( *p ) {
			case '\'': out << "\\'"; break;
			case '\\': out << "\\\\"; break;
			case '\n': out << "\\n"; break;
			case '\r': out << "\\r"; break;
			case '\t': out << "\\t"; break;
			default: out << *p; break;
		}
	}
}

/* Write out a language element name in EBNF format.
 * Handles repeat/list/opt elements by recursively outputting the
 * original element name with the appropriate EBNF suffix. */
static void writeEbnfName( ostream &out, LangEl *lel )
{
	/* Handle generated repeat/list/opt elements */
	if ( lel->repeatOf != 0 ) {
		/* Output the original element name with appropriate EBNF suffix */
		writeEbnfName( out, lel->repeatOf );
		if ( lel->isRepeat )
			out << "*";
		else if ( lel->isList )
			out << "+";
		else if ( lel->isOpt )
			out << "?";
		return;
	}
	
	if ( lel->isLiteral && lel->lit.length() > 0 ) {
		out << "'";
		escapeEbnfString( out, lel->lit );
		out << "'";
	}
	else {
		out << lel->name;
	}
}

/* Write out token definitions from lex blocks */
void Compiler::writeEbnfTokens()
{
	ostream &out = *outStream;
	bool hasTokens = false;
	
	/* Check if there are any tokens to output */
	for ( NamespaceList::Iter ns = namespaceList; ns.lte(); ns++ ) {
		if ( ns->tokenDefList.length() > 0 ) {
			hasTokens = true;
			break;
		}
	}
	
	if ( !hasTokens )
		return;
		
	out << "/* Tokens (regex patterns):\n";
	
	/* Iterate through all namespaces and their tokens */
	for ( NamespaceList::Iter ns = namespaceList; ns.lte(); ns++ ) {
		for ( TokenDefListNs::Iter tok = ns->tokenDefList; tok.lte(); tok++ ) {
			out << " * " << tok->name;
			
			if ( tok->isIgnore )
				out << " (ignored)";
			
			/* For now, we can't easily extract the regex pattern from LexJoin,
			 * so we'll just note that it's defined via regex */
			if ( tok->join != 0 )
				out << ": <regex pattern>";
			else if ( tok->isLiteral )
				out << ": '" << tok->literal << "'";
			
			out << "\n";
		}
	}
	
	out << " */\n\n";
}

/* Write out a production in EBNF format */
void Compiler::writeEbnfProduction( Production *prod )
{
	ostream &out = *outStream;
	
	/* Output production elements */
	for ( ProdEl *el = prod->prodElList->head; el != 0; el = el->next ) {
		if ( el != prod->prodElList->head )
			out << " ";
		writeEbnfName( out, el->langEl );
	}
}

/* Write out all productions for a non-terminal */
void Compiler::writeEbnfLangEl( LangEl *lel )
{
	ostream &out = *outStream;
	
	/* Skip if this is an internal/generated element */
	if ( lel->name.length() > 0 && lel->name[0] == '_' )
		return;
	
	/* Skip repeat/list/opt elements (handled inline) */
	if ( lel->isRepeat || lel->isList || lel->isOpt )
		return;
	
	/* Skip terminals */
	if ( lel->type != LangEl::NonTerm )
		return;
	
	/* Skip elements with no productions */
	if ( lel->prodList.length() == 0 )
		return;
	
	/* Output the non-terminal name */
	out << lel->name << "\n";
	
	/* Output productions */
	bool first = true;
	for ( LelProdList::Iter prod = lel->prodList; prod.lte(); prod++ ) {
		if ( first ) {
			out << "    ::= ";
			first = false;
		}
		else {
			out << "\n      | ";
		}
		
		writeEbnfProduction( prod );
	}
	
	out << "\n\n";
}

/* Main EBNF generation function */
void Compiler::writeEbnfFile()
{
	ostream &out = *outStream;
	
	out << "/* EBNF grammar generated by Colm */\n";
	out << "/* Compatible with https://www.bottlecaps.de/rr/ui */\n\n";
	
	/* Output tokens */
	writeEbnfTokens();
	
	/* Output productions */
	out << "/* Productions */\n\n";
	
	/* Iterate through all language elements */
	for ( LelList::Iter lel = langEls; lel.lte(); lel++ )
		writeEbnfLangEl( lel );
}
